name: Deploy Rental Cozziroam Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        # Remove the cache option until lock file exists
        # cache: 'npm'
    
    - name: Install dependencies and generate lock file
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/"
        target: "~/apps/frontend"
    
    - name: Execute remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/apps/frontend
          pm2 delete frontend || true
          pm2 serve build 3000 --name frontend --spa
          pm2 save